[config]
schemaVersion = "0.0.1"


[package]
namespace = "adamant"
name = "Speedrun_Core"
versionNumber = "1.0.0"
description = "Speedrun modpack coordinator."
websiteUrl = "https://github.com/h2pack-speedrun/adamant-Speedrun_Core"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.78"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-ModUtil = "4.0.1"
adamant-ModpackLib = "1.0.0"
adamant-ModpackFramework = "1.0.0"


# -- submodules-start --
adamant-Speedrun_BugFixesBoons = "1.0.0"
adamant-Speedrun_BugFixesEncounters = "1.0.0"
adamant-Speedrun_BugFixesWeapons = "1.0.0"
adamant-Speedrun_FirstHammer = "1.0.0"
adamant-Speedrun_QoL = "1.0.0"
adamant-Speedrun_RunModsNPCs = "1.0.0"
adamant-Speedrun_RunModsWorld = "1.0.0"
adamant-Speedrun_Timer = "1.0.0"
# -- submodules-end --

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
