[config]
schemaVersion = "0.0.1"


[package]
namespace = "adamant"
name = "ModpackSpeedrunCore"
versionNumber = "1.0.0"
description = "Speedrun modpack coordinator."
websiteUrl = "https://github.com/h2pack-speedrun/ModpackSpeedrunCore"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.78"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-ModUtil = "4.0.1"
adamant-ModpackLib = "1.0.0"
adamant-ModpackFramework = "1.0.0"


# -- submodules-start --
adamant-BugFixesBoons = "0.0.1"
adamant-BugFixesEncounters = "0.0.1"
adamant-BugFixesWeapons = "0.0.1"
adamant-FirstHammer = "1.0.0"
adamant-QoL = "0.0.1"
adamant-RunModsNPCs = "0.0.1"
adamant-RunModsWorld = "0.0.1"
adamant-SpeedrunTimer = "1.0.0"
# -- submodules-end --

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
